<a href="https://colab.research.google.com/github/harshith-murali/Machine-Learning/blob/main/Numpy_Tutorials_Part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

## Numpy Array Operations

In [5]:
arr = np.array([1,2,3,4,5,6,7,8,9])

In [6]:
print("Basic Slicing" , arr[2:7])

Basic Slicing [3 4 5 6 7]


In [7]:
arr_2d = np.array([[1,2,3],[4,5,6], [7,8,9]])

In [8]:
print(arr_2d[0][2])

3


In [9]:
print(arr_2d[2])

[7 8 9]


In [10]:
print(arr_2d[: , 1])

[2 5 8]


# Sorting

In [11]:
unsorted = np.array([3,4,5,1,2,1,1,9,7])

In [12]:
print("Sorted Array" , np.sort(unsorted))

Sorted Array [1 1 1 2 3 4 5 7 9]


In [15]:
arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D array by column \n", np.sort(arr_2d_unsorted , axis=1))

Sorted 2D array by column 
 [[1 3]
 [1 2]
 [2 3]]


## Filter

In [16]:
numbers = np.arange(10)
even_number = numbers[numbers % 2 == 0]

In [18]:
print(even_number)

[0 2 4 6 8]


# Filter with mask

In [19]:
mask = numbers > 5

In [22]:
print(f"Numbers greater than 5 {numbers[mask]}")

Numbers greater than 5 [6 7 8 9]


# Fancy Indexing vs np.where()

In [23]:
indices = [0,2,4]
print(numbers[indices])

[0 2 4]


In [26]:
where_result = np.where(numbers < 5)

In [27]:
print(numbers[where_result])

[0 1 2 3 4]


In [36]:
condition_array = np.where(numbers < 5 , numbers*10+1 , numbers)
print(condition_array)
# print("\nThe condition array",numbers[condition_array])

[ 1 11 21 31 41  5  6  7  8  9]


numbers
[1, 3, 5, 7, 2]

      ↓ check (<5)

[T, T, F, F, T]

      ↓

if True  → number*10+1
if False → original number

↓

[11, 31, 5, 7, 21]

### A simple way to remember np.where
np.where(condition, if_true, if_false)

is the NumPy equivalent of this Python list comprehension:

result = [x * 10 + 1 if x < 5 else x for x in numbers]

# Adding & Removing Data

In [38]:
arr1 = np.array([1,2,3,4])

In [39]:
arr2 = np.array([7,8,9,10])

In [40]:
combined = arr1 + arr2
print(combined)

[ 8 10 12 14]


In [41]:
concat = np.concatenate((arr1, arr2))
print(concat)

[ 1  2  3  4  7  8  9 10]


# Array compatibility

In [43]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,10])

print("Compatibility shapes " , a.shape == b.shape)
print("Compatibility shapes " , a.shape == c.shape)

Compatibility shapes  True
Compatibility shapes  False


# Adding rows & columns

In [44]:
original = np.array([[1,2,3],[4,5,6]])
new_row = np.array([[9,10,11]])

In [45]:
with_new_row = np.vstack((original , new_row))
print("Original Matrix \n ", original)
print("\n New Row Matrix \n" , with_new_row)

Original Matrix 
  [[1 2 3]
 [4 5 6]]

 New Row Matrix 
 [[ 1  2  3]
 [ 4  5  6]
 [ 9 10 11]]


In [46]:

student_marks = np.array([[85, 90, 88],
                          [78, 82, 80]])

attendance = np.array([[95],
                       [98]])

In [47]:
updated_record = np.hstack((student_marks, attendance))

print("Student Marks Matrix\n", student_marks)
print("\nUpdated Record Matrix\n", updated_record)

Student Marks Matrix
 [[85 90 88]
 [78 82 80]]

Updated Record Matrix
 [[85 90 88 95]
 [78 82 80 98]]
