<a href="https://colab.research.google.com/github/harshith-murali/Machine-Learning/blob/main/Numpy_Tutorials%20Part%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

### Creating array from list

In [3]:
arr_1d = np.array([1,2,3,4,5])

In [4]:
print(arr_1d)

array([1, 2, 3, 4, 5])

In [6]:
arr_2d = np.array([[1,2,3,4] , [5,6,7,8]])

In [7]:
arr_2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

# List vs NumPy array

In [8]:
py_list = [1,2,3]
print("Python list multiplication" , py_list * 2)

Python list multiplication [1, 2, 3, 1, 2, 3]


In [9]:
np_array = np.array([1,2,3])
print("Python array multiplication" , np_array * 2)
# element wise multiplication

Python array multiplication [2 4 6]


In [10]:
import time
start = time.time()
py_list = [i*2 for i in range(100000000)]
end = time.time()
print("Time taken for Python list creation:", end - start, "seconds")

Time taken for Python list creation: 16.501644372940063 seconds


In [12]:
py_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [11]:
import time
import numpy as np

start = time.time()
np_array_large = np.arange(100000000)
end = time.time()
print("Time taken for NumPy array creation:", end - start, "seconds")

Time taken for NumPy array creation: 0.4692568778991699 seconds


In [13]:
np_array_large

array([       0,        1,        2, ..., 99999997, 99999998, 99999999])

# create arrays from scratch

In [19]:
zeros = np.zeros((2,3))
print(f" Zeros Array: \n {zeros}" )

 Zeros Array 
[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
ones = np.ones((4,5))
print(f"Ones Array: \n {ones}")

Ones Array 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [22]:
full = np.full((2,2), 7)
print(f"Constant Array: \n {full}")

Constant Array: 
 [[7 7]
 [7 7]]


In [23]:
random = np.random.random((2,3))
print("Random Array \n " , random)

Random Array 
  [[0.06966275 0.68100303 0.58071881]
 [0.81649884 0.52952684 0.41162636]]


In [24]:
sequence = np.arange(0,10,2)
print("Sequence array :\n" , sequence)

Sequence array :
 [0 2 4 6 8]


# Vector , Matrix and Tensor

In [26]:
vector = np.array([1,2,3,4])
vector

array([1, 2, 3, 4])

In [28]:
matrix = np.array([[2,4,6],[3,6,9]])
matrix

array([[2, 4, 6],
       [3, 6, 9]])

In [29]:
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### Array Properties

### store only similar types
<p>Avoid storing different data types </p>

In [35]:
arr = np.array([[1,2,3],[4,5,6]])
print(f"Shape {arr.shape}")
print(f"Size {arr.size}")
print(f"Dimension {arr.ndim}")
print(f"Data Type {arr.dtype}")

Shape (2, 3)
Size 6
Dimension 2
Data Type int64


# Array Reshaping

In [46]:
arr = np.arange(12)
print("Original Array" , arr)
# reshaped = arr.reshape(1, 2) gives error
# reshaped = arr.reshape(8,3) gives error
reshaped = arr.reshape(6,2)
print("Reshaped Array \n" , reshaped)
flattened = reshaped.flatten()
print("\n Flattened Array \n" , flattened)
# return view , instead of copy
raveled = reshaped.ravel()
print("\n Raveled Array" , raveled)

Original Array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array 
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]

 Flattened Array 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled Array [ 0  1  2  3  4  5  6  7  8  9 10 11]


# Transpose

In [48]:
transpose = reshaped.T
print("\n Transposed array \n" , transpose)


 Transposed array 
 [[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]
